// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfnqvthxpoalggedipmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmbnF2dGh4cG9hbGdnZWRpcG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MzEwNjMsImV4cCI6MjA3NDQwNzA2M30.BftF55_OUaW-8EmspUOodeggGoufBac8oEljxy3lZuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});