// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggojyhqwxfukmgehavlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnb2p5aHF3eGZ1a21nZWhhdmxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTc0MjcsImV4cCI6MjA3MjUzMzQyN30.cm9OTNVe2uFSSvf5P8RVjB-yfTIlQ07h_0hPjYeRXQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});